nodes:
  - id: 1
    name: "node1"
    app_addr: "node1:7001"
    pr_addr: "node1:7002"
    http_addr: "node1:8001"

  - id: 2
    name: "node2"
    app_addr: "node2:7001"
    pr_addr: "node2:7002"
    http_addr: "node2:8001"

fanout: 2
num_trees: 3
