[package]
name = "nfs_client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nfs_client"
path = "src/main.rs"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
bincode = "1"
uuid = { version = "1", features = ["v4"] }
common_proto = { path = "../../crates/common_proto" }
deterministic_fs = { path = "../../crates/deterministic_fs" }
